'use client';

import { Fragment, useEffect, useMemo, useState } from 'react';
import { Activity, Aperture, Box, Braces, Camera, CheckCircle2, ChevronDown, CircleDot, Crosshair, Eye, Gauge, Layers3, Orbit, Pause, Play, Radio, Radar, Rotate3D, Satellite, ScanLine, ShieldCheck, Sparkles, Target, TimerReset, TriangleAlert } from 'lucide-react';
import { Button } from '@/components/ui/button';

const scenarios = {
  nominal: { name: 'Nominal tumble', omega: [3.82, -1.14, 2.47], confidence: 96.4, risk: 'CAPTURE VIABLE' },
  glare: { name: 'Solar glare event', omega: [4.61, -0.72, 3.08], confidence: 78.2, risk: 'HOLD / REACQUIRE' },
  occlusion: { name: 'Partial occlusion', omega: [2.94, -1.86, 2.19], confidence: 84.7, risk: 'CONDITIONAL' },
};
type ScenarioKey = keyof typeof scenarios;

function Sparkline({ values, color = '#8fffe7' }: { values: number[]; color?: string }) {
  const key = color.replace('#', '');
  const points = values.map((v, i) => `${(i / (values.length - 1)) * 100},${34 - v}`).join(' ');
  return <svg viewBox="0 0 100 40" preserveAspectRatio="none" className="sparkline" aria-hidden="true"><defs><linearGradient id={`fade-${key}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor={color} stopOpacity=".28"/><stop offset="1" stopColor={color} stopOpacity="0"/></linearGradient></defs><polygon points={`0,40 ${points} 100,40`} fill={`url(#fade-${key})`}/><polyline points={points} fill="none" stroke={color} strokeWidth="1.4" vectorEffect="non-scaling-stroke"/></svg>;
}

function DebrisScene({ running, time, mode, navMode, axes, corridor }: { running: boolean; time: number; mode: ScenarioKey; navMode: 'visual'|'edges'|'thermal'; axes: boolean; corridor: boolean }) {
  const rotation = time * (mode === 'glare' ? 2.5 : 1.7);
  return <div className={`scene ${mode === 'glare' ? 'scene-glare' : ''} scene-${navMode}`}>
    <div className="scan-grid"/><div className="corner corner-tl"/><div className="corner corner-tr"/><div className="corner corner-bl"/><div className="corner corner-br"/>
    <div className="target-meta"><span>OPTICAL CH 01</span><span className="live-dot">LIVE</span></div><div className="range-label">RANGE 18.42 m <span>±0.06</span></div>
    <svg viewBox="0 0 780 500" className="debris-svg" role="img" aria-label="Tracked tumbling rocket body with pose axes and capture corridor">
      <defs><linearGradient id="body" x1="0" y1="0" x2="1" y2="1"><stop stopColor="#d9e7e7" stopOpacity=".58"/><stop offset=".5" stopColor="#506c72" stopOpacity=".22"/><stop offset="1" stopColor="#071214" stopOpacity=".8"/></linearGradient><filter id="glow"><feGaussianBlur stdDeviation="3" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>
      <g opacity=".7" stroke="#83b5b7" strokeWidth="1" fill="none"><ellipse cx="390" cy="255" rx="248" ry="93" strokeDasharray="4 11" transform={`rotate(${rotation*.16} 390 255)`}/><ellipse cx="390" cy="255" rx="184" ry="54" strokeDasharray="2 9" transform={`rotate(${-rotation*.22} 390 255)`}/></g>
      <g transform={`translate(390 255) rotate(${rotation}) translate(-390 -255)`}><polygon points="286,188 474,203 530,254 472,316 282,296 242,242" fill="url(#body)" stroke="#c0e6e3" strokeWidth="1.4"/><ellipse cx="285" cy="242" rx="43" ry="55" fill="#0c1a1d" stroke="#c0e6e3"/><ellipse cx="480" cy="258" rx="52" ry="59" fill="#14292d" fillOpacity=".8" stroke="#c0e6e3"/><path d="M285 188v108M335 192v110M421 199v110M472 204v110M246 240h284" stroke="#9ec9c7" strokeOpacity=".42"/><path d="M265 206l37 13 1 48-40 11M456 218l37 10 8 48-42 20" stroke="#d4f6f0" strokeOpacity=".66"/><circle cx="338" cy="244" r="5" fill="#ffb36b" filter="url(#glow)"/></g>
      {axes&&<g transform="translate(390 255)" strokeWidth="2" filter="url(#glow)"><path d="M0 0L88 -10" stroke="#ff735d"/><path d="M0 0L-30 -76" stroke="#78ffa8"/><path d="M0 0L42 70" stroke="#58b8ff"/><text x="95" y="-10" fill="#ff735d" fontSize="12">X</text><text x="-38" y="-84" fill="#78ffa8" fontSize="12">Y</text><text x="48" y="82" fill="#58b8ff" fontSize="12">Z</text></g>}
      {corridor&&<><g fill="none" stroke="#8fffe7" filter="url(#glow)"><path d="M538 318 C620 342 650 398 707 415" strokeWidth="2" strokeDasharray="7 8"/><path d="M526 330 C602 366 623 420 686 443" strokeOpacity=".35"/><path d="M548 306 C638 322 674 373 725 387" strokeOpacity=".35"/><circle cx="707" cy="415" r="8"/><circle cx="707" cy="415" r="18" strokeOpacity=".4"/></g><text x="588" y="356" fill="#8fffe7" fontSize="11" letterSpacing="1.6">CAPTURE CORRIDOR</text></>}
    </svg>
    <div className="tracking-box"><span>OBJECT ID / COSMOS 1408-C</span></div><div className="camera-mode-tag">{navMode.toUpperCase()} ENHANCEMENT</div>{!running && <div className="paused-tag"><Pause size={13}/> PROPAGATION PAUSED</div>}
  </div>;
}

export default function Home() {
  const [running, setRunning] = useState(true); const [time, setTime] = useState(12.8); const [scenario, setScenario] = useState<ScenarioKey>('nominal'); const [showMath, setShowMath] = useState(false); const [navMode,setNavMode]=useState<'visual'|'edges'|'thermal'>('visual'); const [axes,setAxes]=useState(true); const [corridor,setCorridor]=useState(true); const [armed,setArmed]=useState(false); const current = scenarios[scenario];
  useEffect(() => { if (!running) return; const timer = window.setInterval(() => setTime(t => t >= 60 ? 0 : +(t + .1).toFixed(1)), 100); return () => window.clearInterval(timer); }, [running]);
  useEffect(()=>{const onKey=(event:KeyboardEvent)=>{if(event.target instanceof HTMLInputElement)return;if(event.code==='Space'){event.preventDefault();setRunning(v=>!v)}if(event.key.toLowerCase()==='m')setShowMath(v=>!v);if(['1','2','3'].includes(event.key))setScenario((['nominal','glare','occlusion'] as ScenarioKey[])[+event.key-1])};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[]);
  const windowStart = useMemo(() => Math.max(0, 34.2 - (scenario === 'glare' ? 8.4 : scenario === 'occlusion' ? 3.2 : 0)), [scenario]);
  const translation=[1.284+Math.sin(time*.08)*.09,-.462+Math.cos(time*.11)*.06,18.37-time*.011];
  const quaternion=[Math.cos(time*.014),-.2419+Math.sin(time*.03)*.04,.6031-Math.sin(time*.021)*.05,.2478+Math.cos(time*.026)*.035];
  return <main className="mission-shell">
    <header className="topbar"><div className="brand"><div className="brand-mark"><Orbit size={19}/></div><div><strong>ORBIT/VEIL</strong><span>DEBRIS RENDEZVOUS INTELLIGENCE</span></div></div><div className="mission-id"><span>MISSION</span><strong>ADR-07 / TANGO</strong><ChevronDown size={14}/></div><div className="header-status"><div><Radio size={14}/><span>LINK</span><strong>12.4 Mbps</strong></div><div><TimerReset size={14}/><span>MET</span><strong>04:18:32</strong></div><div className="system-ok"><ShieldCheck size={15}/>NOMINAL</div></div></header>
    <section className="command-row"><div><p className="eyebrow">AUTONOMOUS RENDEZVOUS / PROXIMITY OPS</p><h1>Tumbling Debris<br/><em>Motion Characterization</em></h1><div className="phase-line"><span className="active">01 ACQUIRE</span><i/><span className="active">02 ESTIMATE</span><i/><span>03 SYNCHRONIZE</span><i/><span>04 CAPTURE</span></div></div><div className="scenario-switch" role="group" aria-label="Simulation scenario">{(Object.keys(scenarios) as ScenarioKey[]).map((key,i)=><button key={key} className={scenario===key?'active':''} onClick={()=>setScenario(key)}><span>0{i+1}</span>{scenarios[key].name}</button>)}</div></section>
    <section className="workspace-grid"><div className="visual-panel panel"><div className="panel-head"><div><Aperture size={15}/><span>MONOCULAR NAVCAM</span><b>SYNTHETIC / SPEED+</b></div><div className="view-controls"><span>1280 × 720</span>{(['visual','edges','thermal'] as const).map(view=><button key={view} className={navMode===view?'active':''} onClick={()=>setNavMode(view)} aria-label={`${view} camera mode`}>{view==='visual'?<Camera/>:view==='edges'?<Layers3/>:<Radar/>}</button>)}</div></div><DebrisScene running={running} time={time} mode={scenario} navMode={navMode} axes={axes} corridor={corridor}/><div className="overlay-controls"><button className={axes?'active':''} onClick={()=>setAxes(v=>!v)}><Eye/> BODY AXES</button><button className={corridor?'active':''} onClick={()=>setCorridor(v=>!v)}><Orbit/> CORRIDOR</button><span>STAR TRACKER: LOCKED</span></div><div className="playback"><Button aria-label={running?'Pause simulation':'Play simulation'} onClick={()=>setRunning(!running)} size="icon" className="play-button">{running?<Pause/>:<Play/>}</Button><span className="timecode">T+ {time.toFixed(1)}s</span><div className="timeline"><input aria-label="Prediction time" type="range" min="0" max="60" step=".1" value={time} onChange={e=>{setTime(+e.target.value);setRunning(false)}}/><i style={{left:'43%'}}/><i style={{left:'71%'}}/><span style={{left:'43%'}}>PORT NADIR</span><span style={{left:'71%'}}>CAPTURE</span></div><span className="timecode">T+ 60.0s</span><button className="ghost-action" onClick={()=>setShowMath(true)}><Braces size={15}/> MODEL</button></div></div>
      <aside className="telemetry-panel panel"><div className="panel-head"><div><Activity size={15}/><span>NAVIGATION SOLUTION</span></div><div className="filter-chip"><Sparkles size={12}/> UKF / 120 Hz</div></div><div className="confidence-ring" style={{'--confidence':`${current.confidence*3.6}deg`} as React.CSSProperties}><div><strong>{current.confidence.toFixed(1)}%</strong><span>POSE CONFIDENCE</span></div></div><div className="telemetry-group"><h3><Crosshair/>TRANSLATION <span>CAMERA FRAME / m</span></h3><div className="axis-grid">{translation.map((v,i)=><div key={i}><i className={['x','y','z'][i]}>{['X','Y','Z'][i]}</i><strong>{v>0?'+':''}{v.toFixed(3)}</strong></div>)}</div></div><div className="telemetry-group"><h3><Rotate3D/>ORIENTATION <span>QUATERNION</span></h3><div className="quat">{quaternion.map((v,i)=><Fragment key={i}><span>q{['₀','₁','₂','₃'][i]}</span><b>{v.toFixed(4)}</b></Fragment>)}</div></div><div className="telemetry-group"><h3><Gauge/>ANGULAR VELOCITY <span>deg/s</span></h3><div className="axis-grid compact">{current.omega.map((v,i)=><div key={i}><i className={['x','y','z'][i]}>ω{['₁','₂','₃'][i]}</i><strong>{v>0?'+':''}{(v+Math.sin(time*.05+i)*.08).toFixed(2)}</strong></div>)}</div><Sparkline values={[18,16,17,13,15,10,13,9,12,8,10,7,9,8,6,7]}/></div><div className="telemetry-group inertia"><h3><Box/>INERTIA RATIOS <span>ONLINE ESTIMATE</span></h3><div><span>I₂ / I₁</span><strong>1.284</strong><small>±0.032</small></div><div><span>I₃ / I₁</span><strong>0.762</strong><small>±0.041</small></div></div></aside>
    </section>
    <section className="lower-grid"><div className="panel capture-card"><div className="capture-icon"><Target/></div><div><p className="eyebrow">PREDICTED CAPTURE WINDOW</p><h2>T+ {windowStart.toFixed(1)}s <span>→</span> T+ {(windowStart+8.6).toFixed(1)}s</h2><p>Port normal aligns within 4.2° of the chaser approach vector.</p></div><div className={`viability ${scenario}`}><CircleDot/>{current.risk}</div><button disabled={scenario!=='nominal'} className={`arm-button ${armed?'armed':''}`} onClick={()=>setArmed(v=>!v)}>{armed?<><CheckCircle2/>SEQUENCE ARMED</>:<><Target/>ARM CAPTURE</>}</button></div><div className="panel dynamics-card"><div className="panel-head"><div><ScanLine size={15}/><span>DYNAMICS RESIDUAL</span></div><span>MAHALANOBIS GATE 3σ</span></div><div className="dynamics-content"><Sparkline color="#ffb36b" values={[10,12,11,15,8,9,7,12,8,6,7,5,7,4,5,3]}/><div><strong>{scenario==='nominal'?'0.017':scenario==='glare'?'0.084':'0.046'}</strong><span>FILTER INNOVATION</span></div></div></div></section>
    <section className="ops-grid"><div className="panel event-log"><div className="panel-head"><div><Radar/><span>MISSION EVENT STREAM</span></div><span>UTC 08:14:32.610</span></div><div className="events"><div><time>08:14:31.882</time><CheckCircle2/><span>Target feature track stabilized</span><b>VISION</b></div><div><time>08:14:32.104</time><CheckCircle2/><span>Quaternion innovation inside 3σ gate</span><b>FILTER</b></div><div className={scenario==='nominal'?'':'warning'}><time>08:14:32.416</time>{scenario==='nominal'?<CheckCircle2/>:<TriangleAlert/>}<span>{scenario==='nominal'?'Capture corridor solution converged':'Photometric confidence degraded — hold capture'}</span><b>GNC</b></div></div></div><div className="panel go-nogo"><div><span>VISION</span><b className={scenario==='glare'?'hold':'go'}>{scenario==='glare'?'HOLD':'GO'}</b></div><div><span>DYNAMICS</span><b className="go">GO</b></div><div><span>REL NAV</span><b className={scenario==='occlusion'?'hold':'go'}>{scenario==='occlusion'?'HOLD':'GO'}</b></div><div><span>CAPTURE</span><b className={armed?'go':'standby'}>{armed?'ARMED':'STANDBY'}</b></div></div></section>
    <footer><span>VISION → DIFFERENTIABLE PnP → UKF → EULER PROPAGATION</span><span><Satellite size={13}/> EDGE TARGET: NVIDIA ORIN / 31.8 FPS</span></footer>
    {showMath&&<div className="modal-backdrop" onClick={()=>setShowMath(false)}><section className="math-modal" role="dialog" aria-modal="true" aria-labelledby="math-title" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><p className="eyebrow">PHYSICS MODEL</p><h2 id="math-title">Torque-free rigid-body propagation</h2></div><button onClick={()=>setShowMath(false)} aria-label="Close model">×</button></div><div className="equation">Iω̇ + ω × (Iω) = 0</div><div className="math-grid"><div><span>Principal axis 1</span><b>ω̇₁ = ((I₂ − I₃) / I₁) ω₂ω₃</b></div><div><span>Principal axis 2</span><b>ω̇₂ = ((I₃ − I₁) / I₂) ω₃ω₁</b></div><div><span>Quaternion update</span><b>q̇ = ½ Ω(ω)q</b></div><div><span>Monocular projection</span><b>s pᵢ = K(RPᵢ + t)</b></div></div><p>The filter estimates pose, angular velocity, and inertia ratios together; the simulator propagates them 60 seconds forward to find low-relative-motion capture windows.</p></section></div>}
  </main>;
}
